Bogdanp/django_dramatiq

django_dramatiq/management/commands/rundramatiq.py

This fixes https://github.com/Bogdanp/django_dramatiq/issues/54, where
_get_submodules fails on .tasks modules that contain additional submodules

Convert the module name to a module when recursing in _get_submodules

---

CONTRIBUTORS.md
django_dramatiq/management/commands/rundramatiq.py
tests/test_rundramatiq_command.py

Add support for handling fork-functions. I see two ways to handle this, either via the settings or cli options. Where the first option wouldn't be able to handle different fork functions per running Dramatiq instance.

rundramatiq: handle fork-functions

---

django_dramatiq/apps.py
django_dramatiq/utils.py

This PR replaces `utils.load_class` with Django's `django.utils.module_loading.import_string`.
Since this app is a Django integration, there's no reason to re-create functions already provided by Django.

Use django's existing import-from-string util

---

django_dramatiq/apps.py

ref: https://github.com/pika/pika/blob/3f1a56f56595dc7b933aca2998c6198e8ee9dcb9/CHANGELOG.rst#100-2019-03-26
Or dramatiq is compatible with specific `pika` version?

Remove pika's connection deprecated arguement

---

django_dramatiq/apps.py

Fix bug that attempted to retrieve rate limiter options from results backend options instead of its own settings. Fixes #69

core: update rate limiter to get its own options

---

README.md

`django_dramatiq` works with pip and `poetry add` but not `poetry remove`, so I figured we might as well use the name as it appears on PyPI.

Fix PyPI package name in README

---

.travis.yml
django_dramatiq/__init__.py
setup.py
tox.ini

- Run tests on supported versions of Python and Django
- Drop warning message on django>=3.2
```
RemovedInDjango41Warning: 'django_dramatiq' defines default_app_config = 'django_dramatiq.apps.DjangoDramatiqConfig'. Django now detects this configuration automatically. You can remove default_app_config.
app_config = AppConfig.create(entry)
```

Run tests on supported Python and Django versions.

---

README.md

I was reading the documentation to understand how to add garbage collection for old tasks in my project and I had to spend a few minutes to find from where to import `delete_old_tasks()`
Updated the README with the import path for `delete_old_tasks()`

docs: Add import path for `delete_old_tasks()`

---

.github/workflows/ci.yml

Existing action was triggered only on push, which I presume works only for code maintainers.
This PR changes behaviour to also trigger on new pull requests (same logic as we have in [model_bakery](https://github.com/model-bakers/model_bakery/blob/main/.github/workflows/tests.yml))
I also updated job name to better reflect what is it for (for example, later we could also introduce release.yml for automatic PyPI releases from GitHub actions).

Trigger GitHub Actions on PRs and commits to the main branch

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
django_dramatiq/__init__.py
setup.py
tox.ini

- Added support for Python 3.10 and 3.11
- Added support for Django 4.0 and 4.1
- Dropped support for Python 3.6
- Dropped support for Django 2.2 and 3.1
- Dropped custom app initializer for Django < 3.2
Check https://endoflife.date/python and https://endoflife.date/django for active versions information.

Sync current Python and Django versions

---

django_dramatiq/apps.py
tests/testapp1/apps.py
tests/testapp1/models.py

Bug from #123 was introduced in https://github.com/Bogdanp/django_dramatiq/pull/103 where django_dramatiq started benefitting from `AppConfig.ready()` functionality.
There was a research done in https://github.com/Bogdanp/django_dramatiq/issues/100 explaining the underlying issue.
My PR is using the idea from @dnmellen to call `DjangoDramatiqConfig.ready()` during its models import, so earlier than any other custom models code would be imported.
I was trying to come up with a different way, as this one feels tiny bit "hacky", however could not find anything better.

Fix #123 -- init broker configuration before loading other app models

---

.github/workflows/release.yml

`PYPI_API_TOKEN` needs to be set in GitHub secrets for this action to work.
@Bogdanp may you check this one out at your time and if everything is fine, generate and set a token from PyPI on this repo?
Cheers,
Rust

Add GitHub action to release package on PyPI (Fix #132)

---

django_dramatiq/apps.py

Attempt to simplify and not break dramatiq configuration logic.
Because `AppConfig.ready` is being called rather late,
we added workaround to call `ready()` earlier during model import.
However, this adds complexity and can bring unexpected implications
if someone is overwriting `apps.DjangoDramatiqConfig`.

Replace `AppConfig.ready` workaround with `__init__`

---

README.md

In dramatiq, `DEFAULT_RESULT_TTL = 600_000` which is documented as the 10 minute default. In django_dramatiq, the example uses `"result_ttl": 60_000` which equates to 1 minute.   Although the example shows a customization and not necessarily the defaults, the duration is better communicated by splitting it up into different units. 
Maybe it's just me, but I wasn't sure which units the durations had to be specified in and had to look at the source code / docs.

doc: split magic numbers

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
setup.py
tox.ini

It reached end-of-life:
https://devguide.python.org/versions/

Drop Python 3.7 support

---

django_dramatiq/middleware.py
tests/test_admin_middleware.py

Currently the traceback stored in django admin relies on RetriesMiddleware, if retries is set to 0 or it is disabled, traceback is not stored in django admin, AdminMiddleware should always set traceback without depending on RetriesMiddleware.

Store traceback in django admin

---

setup.py
tox.ini

It reached end-of-life:
https://www.djangoproject.com/download/

Drop Django 4.0 support

---

django_dramatiq/management/commands/rundramatiq.py

it was added in https://github.com/Bogdanp/dramatiq/releases/tag/v1.8.0 , 
and we should also support it.

add skip-logging flag to `rundramatiq` command

---

django_dramatiq/middleware.py

value and tb arguments are required before 3.10
The CI seemed to fail because of this too.

Fix traceback on python 3.8

---

README.md

The `initialize` method does not exist and Django automatically loads apps. Simply adding the app `INSTALLED_APPS` is all there is to it. Tested with `django==4.2.11`. Fixes #157.

Fix CustomDjangoDramatiqConfig example

---

django_dramatiq/admin.py

When using the PickleEncoder make sure the task view still works by showing a representation of the kwargs which is json serializable
This fixes an issue for me when I wasn't able to see the task details
Each kwarg is simply replaced by a string representation if an encoder other than the JSONEncoder is used

Fix for #135 -- when using the PickleEncoder

---

django_dramatiq/management/commands/rundramatiq.py

The defaults for rundramatiq options were hardwired. By using ArgumentDefaultsHelpFormatter, printing the defaults is handled by argparse.

Use ArgumentDefaultsHelpFormatter to show the defaults for rundramatiq options.

---

.github/workflows/release.yml

Usage of sdist and bdist_wheel commands are deprecated and we should use build instead. 
https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#is-setup-py-deprecated

Use python -m build for building dist of package

---

.bumpversion.cfg
setup.py

I would like to remove `bumpversion` as a dependency as the project is ~questionably~ (un)maintained  (see below) and we would need to migrate to a fork-of-the-fork of the project if we want to continue using it. 
However, I question the need for it at all as we only bump the __init__ file and our release process is quite smooth with using the release functionality on github ([recently documented here](https://github.com/Bogdanp/django_dramatiq/blob/master/CONTRIBUTING.md#deploying-a-new-version)).
Any thoughts on this @amureki @Bogdanp ? FYI, I see this is still a dependency on [Dramatiq](https://github.com/Bogdanp/dramatiq/blob/master/setup.py#L84)
Bumpversion status:
- original project (https://github.com/peritus/bumpversion) redirects to -->
- unmaintained fork …

Remove bumpversion

---

README.md
django_dramatiq/management/commands/rundramatiq.py
django_dramatiq/utils.py
setup.cfg
tests/test_rundramatiq_command.py
tests/test_utils.py

Use case: I use rundramatiq to start dramatiq in a docker-compose environment. However, since all my CPUs are detected by docker, I get an excessive number of workers which are slow to restart, but otherwise mostly idling.
With this PR, it is allowed to instruct `rundramatiq` to use a specific number of processes, threads per process via the `DRAMATIQ_NPROCS`, `DRAMATIQ_NTHREADS` environment variables. These variables can be set e.g. in your .env file, where docker-compose will pick them up and pass them to `rundramatiq`.
This would also be useful in general when using `rundramatiq` in any containerized environment, as it is usually preferred to configure software through the environment, rather than modifying the actual command line used by the container.

Allow setting number of processes/threads through DRAMATIQ_NPROCS, DRAMATIQ_NTHREADS.

---

django_dramatiq/admin.py

Simple fix, just like the one for #136 a long time ago.
This week I came across a very similar issue, but this time for the args instead of the kwargs

Fixes #188: when using the PickleEncoder, fix task view for args

---

CONTRIBUTORS.md
django_dramatiq/management/commands/rundramatiq.py
tests/test_rundramatiq_command.py

`--reload` always uses the working directory, added `--watch` so that the directory may be set to another value.
E.g.,
```
$ django-admin rundramatiq --reload
````
Would be the same as:
```
$ django-admin rundramatiq --watch .
```
But we can also now watch alternate directories, E.g.,
```
$ cd /home/tasks && django-admin rundramatiq --watch /opt/myapp/src
```
`--reload` is kept as an alias for `--watch .`, so existing users do not need to change anything.

Allow watch directory to be set via CLI
